# Generated by Django 4.1.7 on 2023-03-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.IntegerField()),
                ("account_name", models.CharField(max_length=500)),
                ("bank_name", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Plan ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("month", "month"),
                            ("bi-weekly", "bi-weekly"),
                            ("6-months", "6-months"),
                            ("year", "year"),
                        ],
                        max_length=50,
                    ),
                ),
                ("property_listings", models.IntegerField()),
                ("premium_listings", models.IntegerField()),
                ("post_boost", models.IntegerField()),
            ],
        ),
    ]
