# Generated by Django 4.1.7 on 2023-03-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_rename_plan_code_paymentplan_plan_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="account_id",
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
