# Generated by Django 5.0.2 on 2024-03-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "payments",
            "0008_alter_payment_options_remove_payment_payment_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="transactionintent",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
