# Generated by Django 5.0.2 on 2024-04-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0009_alter_payment_amount_alter_paymentplan_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionintent",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="CREATED",
                max_length=255,
            ),
        ),
    ]
