# Generated by Django 4.1.4 on 2023-01-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="features",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="location_info",
        ),
        migrations.AddField(
            model_name="apartment",
            name="specifictions",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
