# Generated by Django 4.1.5 on 2023-01-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
