# Generated by Django 4.1.5 on 2023-01-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apartment",
            old_name="location",
            new_name="locality",
        ),
        migrations.AddField(
            model_name="apartment",
            name="area",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apartment",
            name="state",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apartment",
            name="street",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
