# Generated by Django 4.1.3 on 2023-01-18 07:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="guid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="apartment",
            name="property_ref",
            field=models.CharField(default="1234567890", editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="apartment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
