# Generated by Django 4.1.5 on 2023-01-31 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "apartments",
            "0003_rename_location_apartment_locality_apartment_area_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={"verbose_name_plural": "Media"},
        ),
    ]
