# Generated by Django 4.1.5 on 2023-02-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0004_alter_media_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="area",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="locality",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="street",
        ),
        migrations.AddField(
            model_name="apartment",
            name="address",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apartment",
            name="map_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="_type",
            field=models.CharField(
                choices=[("Rent", "Rent"), ("Sale", "Sale")],
                default="Rent",
                max_length=255,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="category",
            field=models.CharField(
                choices=[
                    ("Apartments", "Apartments"),
                    ("Hostels", "Hostels"),
                    ("Flats", "Flats"),
                    ("Commercial Properties", "Commercial Properties"),
                    ("Event Centers", "Event Centers"),
                    ("Self Contain", "Self Contain"),
                    ("Houses", "Houses"),
                ],
                max_length=50,
            ),
        ),
    ]
