# Generated by Django 4.1.7 on 2023-03-21 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0005_remove_apartment_area_remove_apartment_locality_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={"verbose_name": "Video"},
        ),
    ]
