# Generated by Django 4.1.2 on 2023-01-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0005_bookmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="specifications",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
