# Generated by Django 4.1.4 on 2023-01-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0006_alter_apartment_specifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="type",
            field=models.CharField(
                choices=[
                    ("Rent", "Rent"),
                    ("Buy", "Buy"),
                    ("Consultant", "Consultant"),
                ],
                default="Rent",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="category",
            field=models.CharField(
                choices=[
                    ("Bungalow", "Bungalow"),
                    ("Duplex", "Duplex"),
                    ("Flats", "Flats"),
                    ("Self Contain", "Self Contain"),
                    ("Hostels", "Hostels"),
                ],
                max_length=20,
            ),
        ),
    ]
