# Generated by Django 4.1.2 on 2023-01-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0006_alter_apartment_specifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
