# Generated by Django 4.1.7 on 2023-03-23 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0006_alter_media_options"),
    ]
    operations = [
        migrations.AddField(
            model_name="apartment",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apartment",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
