# Generated by Django 4.1.4 on 2023-01-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0007_apartment_type_alter_apartment_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="type",
            field=models.CharField(
                choices=[
                    ("Rent", "Rent"),
                    ("Buy", "Buy"),
                    ("Event Center", "Event Center"),
                ],
                default="Rent",
                max_length=255,
            ),
        ),
    ]
