# Generated by Django 4.1.7 on 2023-04-04 15:30

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0007_apartment_date_created_apartment_date_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="", editable=False, populate_from="title"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="title",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Apartment Title"
            ),
        ),
    ]
