# Generated by Django 4.1.7 on 2023-05-01 22:46

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0008_apartment_slug_alter_apartment_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="", editable=False, populate_from="title", unique=True
            ),
        ),
    ]
