# Generated by Django 5.0.2 on 2024-02-23 23:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0008_apartment_slug_alter_apartment_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.RenameField(
            model_name="apartment",
            old_name="date_created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="apartment",
            old_name="date_updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="media",
            old_name="date_created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="media",
            old_name="date_updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="picture",
            old_name="date_created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="picture",
            old_name="date_updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="date_created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="date_updated",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="bookmark",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookmark",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
