# Generated by Django 4.1.5 on 2023-01-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentdetails",
            name="certificate",
            field=models.ImageField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
