# Generated by Django 4.1.2 on 2023-01-07 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import utils.paths.path_helpers


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_profile_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nin",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="NIN"
                    ),
                ),
                (
                    "id_front",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.paths.path_helpers.get_passport_path,
                        verbose_name="Goverment ID Front",
                    ),
                ),
                (
                    "id_back",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.paths.path_helpers.get_passport_path,
                        verbose_name="Goverment ID Back",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=utils.paths.path_helpers.get_passport_path
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[("NIN", "NIN"), ("GOVERNMENT_ID", "GOVERNMENT_ID")],
                        max_length=50,
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
