# Generated by Django 4.1.2 on 2023-01-07 01:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import utils.validators.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_agentdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentdetails",
            name="agent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_details",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="agentdetails",
            name="nin",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(11),
                    utils.validators.models.validate_NIN_digits,
                ],
            ),
        ),
    ]
