# Generated by Django 4.2.7 on 2023-11-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
