# Generated by Django 4.2.7 on 2023-11-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_user_google_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="date_created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
