# Generated by Django 4.2.7 on 2023-11-26 09:01

from django.db import migrations, models
import django.utils.timezone
import utils.paths.path_helpers
import utils.validators.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_otp_date_created_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentdetails",
            name="id_back",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.paths.path_helpers.get_passport_path,
                validators=[utils.validators.models.validate_file_size],
                verbose_name="Government ID Back",
            ),
        ),
        migrations.AlterField(
            model_name="agentdetails",
            name="id_front",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.paths.path_helpers.get_passport_path,
                validators=[utils.validators.models.validate_file_size],
                verbose_name="Government ID Front",
            ),
        ),
        migrations.AlterField(
            model_name="otp",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
