# Generated by Django 4.2.7 on 2023-11-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_agentdetails_id_back_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="date_created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
