version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build_and_test:
    executor: python/default

    docker:
      - image: cimg/python:3.10.2

    parallelism: 4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
              TEST=$(circleci tests glob "**/test/*.py" | circleci tests split --split-by=timings)
              python manage.py test $TEST --noinput

workflows:
  run-build-test:
    jobs:
      - build_and_test
