# Generated by Django 4.1.4 on 2023-01-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["-date_published"]},
        ),
    ]
