# Generated by Django 4.1.5 on 2023-03-08 22:19

from django.db import migrations, models
import utils.paths.path_helpers


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.paths.path_helpers.get_blogs_image_path,
            ),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
