# Generated by Django 4.1.5 on 2023-01-17 16:48

from django.db import migrations, models
import django.db.models.deletion
import utils.paths.path_helpers


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="image",
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.paths.path_helpers.get_blogs_image_path,
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="blog.blog",
                    ),
                ),
            ],
        ),
    ]
