# Generated by Django 4.1.7 on 2023-03-21 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blog_image_delete_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["-date_published"], "verbose_name": "Post"},
        ),
    ]
