# Generated by Django 5.0.2 on 2024-02-23 23:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_blog_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["-created_at"], "verbose_name": "Post"},
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="date_published",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="date_updated",
            new_name="updated_at",
        ),
    ]
