# Generated by Django 4.1.5 on 2023-03-07 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Notification Description"),
                ),
                (
                    "read",
                    models.BooleanField(
                        default=False, verbose_name="Read Notification"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Payment", "Payment"),
                            ("Chat", "Chat"),
                            ("Advert", "Advert"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=100,
                        verbose_name="Category",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ("-id",),
            },
        ),
    ]
